platform:
  - x64

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  nodejs_version: "7.9.0"
  access_token:
    secure: j+oUaTR28O5BggYTM09pCva2UHkECRwG0zsMBrhg95oMnC/n18asKUHuVJMG6sQA
  github_email:
    secure: zfTP/Yo202a1DXy7wNXFB/1QEY+cHW8l5hGJlq8PT7M=

cache:
  - '%LOCALAPPDATA%\OpenFin\runtime'

install:
  - choco install googlechrome
  - ps: Install-Product node
  - set CI=true
  - appveyor-retry npm install
  - npm build

test_script:
  - node --version
  - npm --version
  - npm run ci
  - ps: .\test-script.ps1


deploy_script:
  - ps: .\deploy-script.ps1

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
